### ISSUE TITLE
Issue with seguranca social calculation

### ISSUE THREAD

**Issue by GeorgesPaul** [SergioEstevao/rnh_tax_calculator#2]
In the calculation for the social security contribution there is no "ceiling" (the maximum amount you can pay to seguranca social). 

However in reality there is a ceiling (which slightly differs year by year). It was 1233,74 EUR for 2022. See https://www.doutorfinancas.pt/simulador-seguranca-social-trabalhadores-independentes-2022/

The minimum contribution calculation is also dependent on this maximum amount. 

From my own manual calculation my conclusion is that when opting for -25% contribution the contribution % of the entire year's turnover is always 9,8%. If that's actually correct, you could simplify your formula and page quite a bit ;) 

I did the manual calculations for 50k, 100k and 150k turnover and my conclusion is that with minimum seg-social contributions you should arrive to about 25% total expenses (IRS + seg social) regardless of income.

**Comment by SergioEstevao** [comment]
Thanks for the information @GeorgesPaul, I will update the code to take in account the ceiling on the Social Security contributions.
